In [1]:
import gymnasium as gym
import gridworld
import numpy as np

def map_to_state(grid_position, grid_size)-> int:
    return grid_position[0] * grid_size + grid_position[1] 

In [2]:
grid_size = 4
env = gym.make('GridWorld-v0', random_start=False, random_goal=False, size=grid_size)

# Array di tutti gli stati
states = np.array([], dtype=int)

# Trasformo tutte le posizioni della griglia in stati
for i in range(grid_size):
    for j in range(grid_size):
        states = np.append(states, map_to_state([i,j], grid_size))

# Counter numero di visite
N = np.full(states.shape, 0)

# Somma di return associati allo stato
S = np.full(states.shape, 0)

# Value function
V = np.full(states.shape, 0.0)

n_episodes = 1000
for episode in range(n_episodes):
    observation, info = env.reset()
    curr_cell = observation['agent']
    curr_state = map_to_state(curr_cell, grid_size)
    done = False
    # Flag stato visitato
    first_time = np.full(states.shape, True)
    # Sequenza EP
    state_seq = np.array([], dtype=int)
    reward_seq = np.array([], dtype=int)
    
    while not done:
        action = env.action_space.sample()
        observation, reward, terminated, truncated, info = env.step(action)   

        done = terminated or truncated
        
        if not done:
            state_seq = np.append(state_seq, curr_state)
            reward_seq = np.append(reward_seq, reward)

        # Next state
        curr_cell = observation['agent']
        curr_state = map_to_state(curr_cell, grid_size)

    for i in range(len(state_seq)):
        s = state_seq[i]
        if first_time[s]:
            first_time[s] = False
            N[s] += 1
            Gt = sum(reward_seq[i::])
            S[s] += Gt
            V[s] = S[s]/N[s]
        
env.close()

V_matrix = V.reshape((grid_size, grid_size))
print(V_matrix)


[[-58.896      -57.12858783 -52.81106613 -48.69686411]
 [-57.98843931 -54.65571914 -50.12688442 -42.66520468]
 [-54.25694444 -48.36759371 -39.64543269 -38.02702703]
 [-49.35993209 -44.22451994 -38.86956522   0.        ]]
