In [6]:
import gymnasium as gym
import gridworld
import numpy as np

def map_to_state(grid_position, grid_size)-> int:
    return grid_position[0] * grid_size + grid_position[1]   

In [8]:
grid_size = 4
n_episodes = 1000

env = gym.make("GridWorld-v0", random_start=True, random_goal=False, size=grid_size)

# Array di tutti gli stati
states = np.array([], dtype=int)

# Trasformo tutte le posizioni della griglia in stati
for i in range(grid_size):
    for j in range(grid_size):
        states = np.append(states, map_to_state([i,j], grid_size))

# Guess iniziale della value function 
V = np.full(states.shape, 0.0)
alpha = 0.2
gamma = 1


# Sampling
for i in range(n_episodes):
    observation, info = env.reset()
    done = False
    curr_cell = observation['agent']
    goal_cell = observation['target']

    if np.array_equal(curr_cell, goal_cell):
        print('Error! START == GOAL')
    curr_state = map_to_state(curr_cell, grid_size)
    
    while not done:
        # Eseguo uno step avanti
        action = env.action_space.sample()
        observation, next_reward, terminated, truncated, info = env.step(action)
        next_cell = observation['agent']
        next_state = map_to_state(next_cell, grid_size)

        V[curr_state] = V[curr_state] + alpha * (next_reward + gamma * V[next_state] - V[curr_state])
        done = terminated or truncated
        curr_state = next_state
        
V_matrix = V.reshape((grid_size, grid_size))
print(V_matrix)

[[-63.48310756 -60.45167808 -56.42717339 -51.68893867]
 [-60.31675839 -58.73371422 -51.69690901 -42.74012462]
 [-56.68102476 -54.98407117 -41.80495216 -21.07711644]
 [-52.2689768  -39.35071385 -25.09799679   0.        ]]
